# Generated by Django 5.2.4 on 2025-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='queryy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
